FROM python:3.10

WORKDIR /app

COPY requirements.txt clear_venv.sh ./

RUN pip install -r requirements.txt && \
    mkdir -p /src && python3 -m venv /venv && \
    chmod u+x clear_venv.sh

COPY . .

CMD ["python", "server.py"]